server:
  port: 8081
spring:
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:mysql://finance.wangchenyu.net.cn/finance
    username: fnuser
    password: fnpass
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect